services:
  marimekko-app:
    container_name: marimekko-app
    build:
      context: .
      dockerfile: ./Dockerfile.development
    env_file:
      - .env.development
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    restart: always
    ports:
      - 3000:3000
    networks:
      - marimekko-network
    depends_on:
      - marimekko-db

  marimekko-db:
    container_name: marimekko-db
    platform: linux/amd64
    image: postgres:17.2-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - marimekko-data:/var/lib/postgresql/data/
    restart: unless-stopped
    ports:
      - '5432:5432'
    networks:
      - marimekko-network

volumes:
  marimekko-data:

networks:
  marimekko-network:
    driver: bridge
